/**
 * Created by Administrator on 2016/6/14.
 */
//专业分类数据
var GLOBAL=GLOBAL||{};
GLOBAL.classifyData = [
    {
        "name":"前端语言",      //专业名称
        "classifyCode":"1",   //专业分类所对应的专业代号值，唯一
        "fatherCode":null     //父级的classifyCode，第一级分类没有上级，所以为null
    },{
        "name":"后端语言",
        "classifyCode":"2",
        "fatherCode":null
    },{
        "name":"html",
        "classifyCode":"3",
        "fatherCode":"1"
    },{
        "name":"css",
        "classifyCode":"4",
        "fatherCode":"1"
    },{
        "name":"javascript",
        "classifyCode":"5",
        "fatherCode":"1"
    },{
        "name":"java",
        "classifyCode":"6",
        "fatherCode":"2"
    },{
        "name":"php",
        "classifyCode":"7",
        "fatherCode":"2"
    },{
        "name":"nodejs",
        "classifyCode":"8",
        "fatherCode":"2"
    }
];

//表格数据
//表格数据
GLOBAL.tableData = {
    "pageStart":0,
    "pageSize":10,
    "count":15,
    "list0":[{
        "title":"html基础1",
        "nomber":"yysd4568",
        "courseId":"1",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础2",
        "nomber":"yysd4568",
        "courseId":"2",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础3",
        "nomber":"yysd4568",
        "courseId":"3",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础4",
        "nomber":"yysd4568",
        "courseId":"4",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础5",
        "nomber":"yysd4568",
        "courseId":"5",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础6",
        "nomber":"yysd4568",
        "courseId":"6",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础7",
        "nomber":"yysd4568",
        "courseId":"7",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础8",
        "nomber":"yysd4568",
        "courseId":"8",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础9",
        "nomber":"yysd4568",
        "courseId":"9",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础10",
        "nomber":"yysd4568",
        "courseId":"10",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    }],
    "list10":[{
        "title":"html基础11",
        "nomber":"yysd4568",
        "courseId":"11",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础12",
        "nomber":"yysd4568",
        "courseId":"12",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础13",
        "nomber":"yysd4568",
        "courseId":"13",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础14",
        "nomber":"yysd4568",
        "courseId":"14",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    },{
        "title":"html基础15",
        "nomber":"yysd4568",
        "courseId":"15",
        "classify":"前端",
        "publishAt":"2014/05/09",
        "createAt":"2014/05/09",
        "status":2
    }]
}